---
title: "Tidy Tuesday- Mt. Everest Climb Duration and Outcome"
author: ''
date: '2020-09-24'
slug: tidy-tuesday-mt-everest-climb-duration-and-outcome
tags: []
categories: Tidy Tuesday
---

For this Tidy Tuesday challenge I looked at the duration of Mt. Everest climbs in days and their outcome (success or failure) over the past century.  Looking at the plot, it seems like you want to get in and out within 50-60 days!

```{r set up for everest climbs, echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(tidytuesdayR)
library (lubridate)
library (ragg)

#Get data
tuesdata <- tidytuesdayR::tt_load(2020, week = 39)
expeditions <- tuesdata$expeditions

```


```{r data wrangling for everest, echo=FALSE, warnings = FALSE, message= FALSE}
expeditions$Outcome <- as.factor (expeditions$termination_reason)
expeditions$Outcome <- recode (expeditions$Outcome, 
                               "Accident (death or serious injury)" = "Failure",
                               "Bad conditions (deep snow, avalanching, falling ice, or rock)" = "Failure",
                               "Attempt rumoured" = "Failure",
                               "Bad weather (storms, high winds)" = "Failure",
                               "Did not attempt climb" = "Failure",
                               "Did not reach base camp" = "Failure",
                               "Illness, AMS, exhaustion, or frostbite" = "Failure",
                               "Lack (or loss) of supplies or equipment" = "Failure",
                               "Lack of time" = "Failure",
                               "Other" = "Failure",
                               "Route technically too difficult, lack of experience, strength, or motivation" = "Failure",
                               "Success (claimed)" = "Success",
                               "Success (main peak)" = "Success",
                               "Success (subpeak)" = "Success",
                               "Unknown" = "Failure")

#helpful for working with lubridate https://data.library.virginia.edu/working-with-dates-and-time-in-r-using-the-lubridate-package/

everest <- filter (expeditions, peak_name == "Everest")
everest$start <- as.Date (everest$basecamp_date, format = "%Y%m%d")
everest$peak <- as.Date (everest$highpoint_date, format = "%Y%m%d")
everest$term <- as.Date (everest$termination_date, format = "%Y%m%d")
everest$time.interval <-  everest$start %--% everest$term
everest$trip_dur <- as.duration(everest$time.interval)
everest$days<- everest$trip_dur/ddays(1)
everest_sm <- select (everest, expedition_id, Outcome, year, days) %>%
  group_by (year, Outcome) %>%
  summarize (meandays = mean(days, na.rm = TRUE))

```


```{r everest plot, echo=FALSE, warning=FALSE, message=FALSE}

plot <- ggplot (everest_sm, aes (x=year, y=meandays, group = Outcome,
                         fill = Outcome, 
                         groups = 2))+
  geom_bar (position = "stack", stat = "identity") +
  scale_fill_manual (values = c("midnightblue", "firebrick"))+
  labs (title = "Don't stay on Mt. Everest too long", subtitle = "Average Length of Trip and Outcome",
        y = " ",
        x = " ",
        caption = "From the Himalayan Dataset | Visualization by: @joieprout" ) +
  annotate ("text", x = 1955, y = 80, size = 2.5, label = "Most successful climbs \nare around 50 days") +
  theme_classic(base_size = 10) +
  theme (plot.title = element_text (size = 12,face = "bold"),
         panel.grid = element_blank (),
         panel.background = element_rect (fill = "gray98"),
         plot.background = element_rect (fill = "gray98"),
         axis.text = element_text (color = "black"),
         plot.margin = unit (c(0.2, 0.4, 0.2, 0.4), "cm"),
         legend.title = element_blank (),
         legend.position = "top",
         legend.direction = "horizontal",
         legend.background = element_rect (fill = "gray98")) +
  geom_hline (yintercept = 50, linetype = "dashed", color = "red")
print (plot)
```
```


